### ISSUE TITLE
add silly as a language

### ISSUE THREAD

**Issue by cheesykirah** [KaylinOwO/Project-Apparatus#102]
im willing to provide the translations

**Comment by Toaaa** [comment]
If you want to add the language, you can find the files [here](https://github.com/KaylinOwO/Project-Apparatus/tree/main/ProjectApparatus/Lang)

**Comment by cheesykirah** [comment]
[silly_UWU.txt](https://github.com/KaylinOwO/Project-Apparatus/files/14016377/silly_UWU.txt)
github no likey resx so had to change file format uwu implement right meow or i will alert IRS of u

**Comment by Toaaa** [comment]
Ok

**Comment by cheesykirah** [comment]
![Unbenweranntfgd (1)](https://github.com/KaylinOwO/Project-Apparatus/assets/78316436/43a0b665-5139-4462-913a-752058bea494)
