### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by myfirstevercode** [KaylinOwO/Project-Apparatus#11]
add more troll option for team, like attack them using ai monster, or hunt them using ai monster

**Comment by myfirstevercode** [comment]
possible to play monster sounds to troll team

**Comment by Anonymous691-source** [comment]
- Troll Options -
Turn Lights On And Off
Turn Loud Horn On And Off
- Kill Self Options - ( not necessary but just add them )
Kill Effect Like Coil Head Or Ghost Girl
- Spawning Options -
- Spawn Valuable Scrap Like Gold that cost 102
- Spawn Enemy 
- Spawn More Scrapts ( in the dungeon )


( if some of these suggestions are not possible then dont use them )

**Comment by tedzify** [comment]
- Self Tab
  - **Invisible to monsters:** Monsters cannot detect the player
  - **Melee damage:** Change the player's melee damage multiplier
  - **Magic Hand:** Place a random item on the map into the player's inventory
- Misc Tab
  - **Enlarge item interaction box:** Enlarges items interaction box to make it easier to pick up small items from far away.
  - **Kill/Destroy nearby monsters, turrets, mines:** Adds a hotkey to kill/destroy any nearby monsters in a set range or radius from the player
- Monster tab (suggestion): Add a monster tab to allow easy access to features that are related to monsters. This contains the list of all monsters on the map, you can click on a monster and it will show the options of what you can do with them similar to the 'Player tab'
  - **Teleport monster to player:** Teleport selected monster to the selected player
  - **Lure monster to player:** Forces the selected monster to pathfind to the selected player
  - **Kill/Destroy monster:** Kills/destroy selected monsters with a singer button
