### ISSUE TITLE
[Bug]: Turrents not working

### ISSUE THREAD

**Issue by JuanCalle1606** [KaylinOwO/Project-Apparatus#110]
### Describe the bug

When i host a game turrents dont work.

I got this spammed on console all the time causing a lot of lag:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Turret_CheckForPlayersInLineOfSight_Patch.Prefix (GameNetcodeStuff.PlayerControllerB& __result) (at <ad69ed8a8aac45d4825e2cab86853901>:0)
(wrapper dynamic-method) Turret.DMD<Turret::CheckForPlayersInLineOfSight>(Turret,single,bool)
Turret.Update () (at <af9b1eec498a45aebd42601d6ab85015>:0)

### Steps To Reproduce

1. Inject
2. Host a game
3. Stay in front of a turrent, it dont activate

### Expected Behavior

Turrents works and dont get lag because of error spam.

**Comment by TheGreenBandit** [comment]
Will fox, also need to fix thumper going after u in untargetable and mouthdog detecting noise.

**Comment by TheGreenBandit** [comment]
Solved @Toaaa
