### ISSUE TITLE
config doesnt save

### ISSUE THREAD

**Issue by legalizetren** [KaylinOwO/Project-Apparatus#12]
using the latest UC release, setting stuff up, but doesnt seem to load back up once i reinject. idk why, doesnt save any config file to my folder too

**Comment by LordIgnis** [comment]
the latest UC version doesn't because for some reason that feature was breaking the game for just about everybody causing black screens, but has since been fixed as of last night to my testing if you compile it manually from github

**Comment by KaylinOwO** [comment]
This isn't present in the latest from the repo so I'm going to close the issue
