### ISSUE TITLE
[report]: not about the project apparatus, but about discord

### ISSUE THREAD

**Issue by dyannn27** [KaylinOwO/Project-Apparatus#128]
### Describe the bug

hi, since yesterday, i haven’t been able to join your discord. what’s going on? i used to be a member but i left, and now i want to rejoin. lastly, i’d like to ask if there’s a video or tutorial on how to update the project apparatus using visual studio? i found a video on uc, but it seems outdated because i tried it and it didn’t work.
![Screenshot 2024-12-14 231418](https://github.com/user-attachments/assets/245ea561-5d94-4752-9913-5e09c6a89042)

 

### Steps To Reproduce

-

### Expected Behavior

-

### Additional context

-

**Comment by Toaaa** [comment]
Hi. First, please comment your discord tag below so i can look further into your issue. Second, you can "update" project apparatus by simply pulling the latest version from GitHub and building it inside of vs.

**Comment by dyannn27** [comment]
1. discord name: dyannn
2. actually, i've tried what you told me several times, but it still doesn't work. i don't know if i'm doing it right or wrong. maybe you can check the video in this link to correct me if what i'm doing is correct or not -> https://pixeldrain.com/u/D7tbgAfk

**Comment by Toaaa** [comment]
According to Discord, you've received an automated ban due to spam. This ban should now be lifted. Please join the Discord server again and create a ticket so that we can fix your issue with the building.
![tfvwv](https://github.com/user-attachments/assets/af676ff5-4a4b-4628-89d8-55764df27469)

**Comment by dyannn27** [comment]
i'm really sorry, maybe my account was hacked back then and sent something. thank u for helping me ^_^
