### ISSUE TITLE
How do you open the menu?

### ISSUE THREAD

**Issue by NebulaShinx** [KaylinOwO/Project-Apparatus#13]
I followed the V2 instructions, and the name "ProjectApparatus" shows on the top left, but how do I open the menu? Do I press a certain key on my keyboard? On the video it looked like it automatically opened, but mine did not.

Thank you! 

@KaylinOwO @Toaaa @AnonGajo

**Comment by NebulaShinx** [comment]
![Screenshot 2023-12-30 133125](https://github.com/KaylinOwO/Project-Apparatus/assets/119905704/ca532c06-5f14-49b5-aee7-8fb11a8cddfe)

**Comment by NebulaShinx** [comment]
I figured it out, but thank you anyway!

**Comment by Toaaa** [comment]
> so how do you open it ?

After injecting, you need to press the `INSERT` key on your keyboard to open and close the menu.
