### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Aiozlove** [KaylinOwO/Project-Apparatus#23]
Error CS0103: The name "JsonUtility" does not exist in the current context

**Comment by Aiozlove** [comment]
I tried to solve this problem, but the screen went black after I injected it

**Comment by Toaaa** [comment]
Try to download and compile the [latest version](https://codeload.github.com/KaylinOwO/Project-Apparatus/zip/refs/heads/main). You can find a tutorial [here](https://www.youtube.com/watch?v=6AhJQLgt8Jc).
