### ISSUE TITLE
Where is the saved setting/config stored

### ISSUE THREAD

**Issue by Unk88** [KaylinOwO/Project-Apparatus#24]
Where is the cfg file/ saved settings i bugged it it out with the toggle no clip and cant seem it fix it ever after delete everything
and re compile ect

**Comment by Toaaa** [comment]
The config file is located at `C:\Users\%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company\PASettings.json`

**Comment by Unk88** [comment]
ty and cool menu

**Comment by a66a66a** [comment]
> 配置檔位於`C:\Users\%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company\PASettings.json`

thanks you
