### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Anonymous691-source** [KaylinOwO/Project-Apparatus#26]
Troll Options -

Turn Lights On And Off
Turn Loud Horn On And Off
Kill Self Options - ( not necessary but just add them )
Kill Effect Like Coil Head Or Ghost Girl

Spawning Options -

Spawn Valuable Scrap Like Gold that cost 102
Spawn Enemy
Spawn More Scrapts ( in the dungeon )

( if some of these suggestions are not possible then dont use them )

**Comment by Toaaa** [comment]
`Kill Self Options` have already been added in the [latest version](https://github.com/KaylinOwO/Project-Apparatus/commit/3e06da4c277a397443e85f7582dd8b9860f718dc#diff-52fccca788d7f40756cb983693e645af6561c4d2b1e18a309291fe19eda9ee1eR2).
