### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jezbud** [KaylinOwO/Project-Apparatus#29]
Control monster

Teleport other players to locations/other players

Inverse teleport player

teleport all monsters to selected player

make all monsters target player

**Comment by Toaaa** [comment]
"Control monster" was added in the [latest version](https://github.com/KaylinOwO/Project-Apparatus/commit/3e06da4c277a397443e85f7582dd8b9860f718dc).

**Comment by KaylinOwO** [comment]
You can't teleport other players without host afaik and I want to avoid adding a lot of host options - at least for now.
