### ISSUE TITLE
MAKE THE CHEAT PERMANENT pls (suggestion)

### ISSUE THREAD

**Issue by endervale** [KaylinOwO/Project-Apparatus#31]
you need to inject everytime you wanna play sucks, cant you make like other cheats that arent so complete as this one and use injectors like BepInEx to make it permanent, so after you close the game you wont need to inject it aggain

**Comment by Toaaa** [comment]
No. We currently have no plans on providing BepInEx support or a modified version of the Assembly-CSharp.

**Comment by endervale** [comment]
> No. We currently have no plans on providing BepInEx support or a modified version of the Assembly-CSharp.

ok but do you have plans of making it permanent ?
