### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Stepd3D** [KaylinOwO/Project-Apparatus#33]
I pressed in the SELF tab !unbound! and now it freeze...

**Comment by Toaaa** [comment]
Hi, I can bind and unbind the `Thirdperson` and the `Noclip` option in the `Self` tab without any problems. If you still have the problem, please try the [latest version](https://codeload.github.com/KaylinOwO/Project-Apparatus/zip/refs/heads/main) of the cheat.

**Comment by KaylinOwO** [comment]
Should be fixed
