### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SquattingDoggo** [KaylinOwO/Project-Apparatus#38]
after possessing monsters, if u enable 3 person u cant see self menu anymore

**Comment by SquattingDoggo** [comment]
![Screenshot_33](https://github.com/KaylinOwO/Project-Apparatus/assets/155449930/15f2f51d-4551-48eb-8004-7e230293f2f1)

**Comment by SquattingDoggo** [comment]
can't interact with nothing anymore, where is the config file?

**Comment by crimsonclientonotp** [comment]
@SquattingDoggo You have to go into the code and delete savesettings and loadsettings. I have done this myself, now it does not save when I load up the game. It saves me from glitches.

**Comment by crimsonclientonotp** [comment]
It will be in hacks.cs

**Comment by crimsonclientonotp** [comment]
Ill get a ss rq

**Comment by crimsonclientonotp** [comment]
@SquattingDoggo It is in Settings.cs and you delete these 2 things. It will be right by the bottom when you find it. Your welcome!
![image](https://github.com/KaylinOwO/Project-Apparatus/assets/151975517/fb5be8fa-aa04-4054-81c5-5c45d7a154cc)

**Comment by SquattingDoggo** [comment]
> @SquattingDoggo It is in Settings.cs and you delete these 2 things. It will be right by the bottom when you find it. Your welcome! ![image](https://private-user-images.githubusercontent.com/151975517/293752108-fb5be8fa-aa04-4054-81c5-5c45d7a154cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTkyNzcsIm5iZiI6MTcwNDIxODk3NywicGF0aCI6Ii8xNTE5NzU1MTcvMjkzNzUyMTA4LWZiNWJlOGZhLWFhMDQtNDA1NC04MWM1LTVjNDVkN2ExNTRjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxODA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzBkZjY1NWI0YTgxODY2M2RlMWQ1MDliMGFiYzEyZjU4MWMwZmY0N2NhNWNmNTRmZDEzMjE3ZmFhYjEyOTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HaAqfEJdaW7VID7hfel0aMyXvsikbYrEraP71RD_cII)

ty

**Comment by KaylinOwO** [comment]
Sorry I suppose I should've done more testing last night, I'll take a look at it soon.

**Comment by KaylinOwO** [comment]
> @SquattingDoggo You have to go into the code and delete savesettings and loadsettings. I have done this myself, now it does not save when I load up the game. It saves me from glitches.
Just delete PASettings.json in C:\Users\%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company

**Comment by KaylinOwO** [comment]
I believe the issue should be fixed - please test now
