### ISSUE TITLE
Function improvements

### ISSUE THREAD

**Issue by Taogun** [KaylinOwO/Project-Apparatus#39]
1.Highlight view mode
2.Out-of-body or ghost mode
3.Possess  Enemy' to Self tab - Note: You will be visibily within the enemy.
I hope that when controlling the monster, my own model will not overlap with the monster. This makes it easy to see that you are a cheater. I achieved this in other cheat menus. He did it by being in an out-of-body state and then Control monsters.In soul mode, I control the monster by pointing at it and pressing the mouse wheel, and it is in third person. I can also make the monster fly up and climb stairs by pressing the space button.
4.Please bind a shortcut key to the possess enemy function so that it will be more convenient.
5.The screen freeze occurs when controlling the monster is not finished and then exits the battle and returns to the main interface.

**Comment by VOLEURMESSI** [comment]
it is well known that the people of this country are most skilled at piracy and theft.
right.. a thief from China. lol

**Comment by Taogun** [comment]
> it is well known that the people of this country are most skilled at piracy and theft. right.. a thief from China. lol

Hey bro，it is an open project and free for everyone，i just want this project be better，i never get any benefits from this project i promise，what is wrong with me？

> 众所周知，这个国家的人民最擅长海盗和盗窃。对...一个来自中国的小偷。哈哈

**Comment by VOLEURMESSI** [comment]
just because you come from a country known for theft.
I believe that everything your do is purposeful.

**Comment by AnonGajo** [comment]
> just because you come from a country known for theft. I believe that everything your do is purposeful.
Just because he's Chinese doesn't mean he can't make a request.
Hope you take some time to reflect on your words.
Don't leave comments like that here, they're not welcome.

**Comment by Taogun** [comment]
> > 仅仅因为你来自一个以盗窃闻名的国家。我相信你所做的一切都是有目的的。
> 
> 仅仅因为他是中国人并不意味着他不能提出要求。 希望你花点时间反思一下你的话。 不要在这里留下这样的评论，他们不受欢迎。

I praise your words！thank you！

**Comment by Taogun** [comment]
> 希望

是的真的厚颜无耻这种人，坑蒙拐骗套个壳就值大几百
![Uploading Screenshot_20240103_155845.jpg…]()
