### ISSUE TITLE
upon injection game screen freezes at last frame before injection.

### ISSUE THREAD

**Issue by roycethegod** [KaylinOwO/Project-Apparatus#4]
followed steps in video to a tee and yet am met with freezing. i am aware you are trying to fix this. perhaps talk with someone that has the issue and see if you can fix it then. thank you.

**Comment by KaylinOwO** [comment]
This is very odd, I thought the issue was solved. This is like the third time I've thought it to be fixed and someone else comes back to say it's happening to them.  I imagine there must be more than one cause and it's hard to fix something without being able to replicate it.

**Comment by roycethegod** [comment]
i have redownloaded the game and downloaded everything you have provided and yet this issue is still occuring

**Comment by ghtg** [comment]
Same error. Please compile and upload release version where it fixed.

**Comment by ghtg** [comment]
After injection it spamming errors in console:
[Warning: Unity Log] Render Pipeline error : the XR layout still contains active passes. Executing XRSystem.EndLayout() right now.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Fog_IsVolumetricFogEnabled_Patch.Prefix (UnityEngine.Rendering.HighDefinition.Fog __instance, System.Boolean& __result) (at <fcd7b2222cc8474894bbe9ae33f5364c>:0)
(wrapper dynamic-method) UnityEngine.Rendering.HighDefinition.Fog.DMD<UnityEngine.Rendering.HighDefinition.Fog::IsVolumetricFogEnabled>(UnityEngine.Rendering.HighDefinition.HDCamera)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.ReinitializeVolumetricBufferParams (UnityEngine.Rendering.HighDefinition.HDCamera hdCamera) (at <b8abf62aeac646cea5c5cde032ff9314>:0)
UnityEngine.Rendering.HighDefinition.HDCamera.Update (UnityEngine.Rendering.HighDefinition.FrameSettings currentFrameSettings, UnityEngine.Rendering.HighDefinition.HDRenderPipeline hdrp, UnityEngine.Experimental.Rendering.XRPass xrPass, System.Boolean allocateHistoryBuffers) (at <b8abf62aeac646cea5c5cde032ff9314>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.TryCalculateFrameParameters (UnityEngine.Camera camera, UnityEngine.Experimental.Rendering.XRPass xrPass, UnityEngine.Rendering.HighDefinition.HDAdditionalCameraData& additionalCameraData, UnityEngine.Rendering.HighDefinition.HDCamera& hdCamera, UnityEngine.Rendering.ScriptableCullingParameters& cullingParams) (at <b8abf62aeac646cea5c5cde032ff9314>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.PrepareAndCullCamera (UnityEngine.Camera camera, UnityEngine.Experimental.Rendering.XRPass xrPass, System.Boolean cameraRequestedDynamicRes, System.Collections.Generic.List`1[T] renderRequests, UnityEngine.Rendering.ScriptableRenderContext renderContext, UnityEngine.Rendering.HighDefinition.HDRenderPipeline+RenderRequest& renderRequest, UnityEngine.CubemapFace cubemapFace) (at <b8abf62aeac646cea5c5cde032ff9314>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext renderContext, System.Collections.Generic.List`1[T] cameras) (at <b8abf62aeac646cea5c5cde032ff9314>:0)
UnityEngine.Rendering.RenderPipeline.InternalRender (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipe, System.IntPtr loopPtr, UnityEngine.Object renderRequest) (at <e27997765c1848b09d8073e5d642717a>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Hacks.OnGUI () (at <fcd7b2222cc8474894bbe9ae33f5364c>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Hacks.OnGUI () (at <fcd7b2222cc8474894bbe9ae33f5364c>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Hacks.Update () (at <fcd7b2222cc8474894bbe9ae33f5364c>:0)

**Comment by AnonGajo** [comment]
Download the latest source, and make sure 0Harmony is added as an **Embedded Resource**.

![image](https://github.com/KaylinOwO/Project-Apparatus/assets/153150071/a5731685-04aa-4fe6-83ac-831564543a27)
