### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Taogun** [KaylinOwO/Project-Apparatus#42]
![IMG_20240103_002043](https://github.com/KaylinOwO/Project-Apparatus/assets/155458839/e134f92f-6cd5-4cb3-9b07-2ee55f765c73)
![IMG_20240103_002304](https://github.com/KaylinOwO/Project-Apparatus/assets/155458839/1cbde21c-2df2-45ff-8ea1-a346ba27ab33)
![IMG_20240103_002310](https://github.com/KaylinOwO/Project-Apparatus/assets/155458839/29b76370-4dff-40a0-896f-fb77b1b50717)

Player Esp doesn't work for some players
And I can’t see them in the player list.

**Comment by KaylinOwO** [comment]
I suspect this is to do with mods and for now we won't be fixing anything to do with mods.
