### ISSUE TITLE
Visual Suggestion

### ISSUE THREAD

**Issue by zerevoidd** [KaylinOwO/Project-Apparatus#45]
Please add a way to remove the pixelly filter that's displayed by default, game looks so much nicer that way. (this filter is removed when going into third person but it'd be nice to use in first person as well.

**Comment by vOuii** [comment]
Just use the HD Textures mod..?

**Comment by KaylinOwO** [comment]
Added "Full Render Resolution" option in Graphics tab

**Comment by zerevoidd** [comment]
Thank you this looks awesome
