### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Taogun** [KaylinOwO/Project-Apparatus#49]
May I ask if updating only involves replacing the file？

**Comment by Anonymous691-source** [comment]
no.

**Comment by Anonymous691-source** [comment]
if you replace it. it wont work 
and wont update ive tried it

**Comment by KaylinOwO** [comment]
> if you replace it. it wont work and wont update ive tried it

What? if you replace the files from v47 (latest beta) with the ones you already have in the Resources folder it should work fine, worked for me when I tried it but I didn't do that much testing.

**Comment by Taogun** [comment]
> 如果你更换它。它不会工作 ，也不会更新我试过了

How can ？I succeed 。Is your method wrong, and after replacing it, you have to run ProjectApparatus.sln again to generate the solution, this step is very important and there is no effect without this step

**Comment by Taogun** [comment]
> > 如果你更换它。它不会工作，也不会更新我试过了
> 
> 什么？如果您将 v47（最新测试版）中的文件替换为 Resources 文件夹中已有的文件，它应该可以正常工作，当我尝试它时对我有用，但我没有做太多测试。

Maybe we dont say the same thing.I'm talking about how to upgrade 1.1.16 to 1.1.17 instead of changing with the update of the game version

**Comment by vOuii** [comment]
Bruh... why do you exist on github. You clearly have to build it every time there is an update to the hub files. And if the game updates, then the offsets of the cheat may break too so the cheat will need updating too eventually
