### ISSUE TITLE
Not an issue, but please read

### ISSUE THREAD

**Issue by NebulaShinx** [KaylinOwO/Project-Apparatus#5]
@KaylinOwO @AnonGajo 

I am sorry for posting this as an issue when it's not, but I don't know what to do with the file after I download it? Like how do I get it onto Lethal Company so I can use it? 

Thank you!

- NebulaShinx

**Comment by AnonGajo** [comment]
There's a YouTube tutorial on how to build & inject the source.
https://www.youtube.com/watch?v=0DmMXbVzPtQ

**Comment by KaylinOwO** [comment]
Look at the bottom of the UC thread for links to Harmony and the injector https://www.unknowncheats.me/forum/other-fps-games/616587-project-apparatus-lethal-company-cheat.html

**Comment by NebulaShinx** [comment]
Thank you so much!

**Comment by NebulaShinx** [comment]
It will not let me open the injector folder or extract it
