### ISSUE TITLE
Keybind for "noclip" is broken.

### ISSUE THREAD

**Issue by M-Gardevoir** [KaylinOwO/Project-Apparatus#53]
Hello !

I saw you fixed the night mode and thanks for that ! but i can't manage to fix the keybind bug going on here. It does bind to the select key but pressing the keybind does nothing.

Looks like the new baby system keybind broky ! I reverted back to the old method to make it works.

**Comment by KaylinOwO** [comment]
I can't replicate and don't see why the old system would work and the new one wouldn't. Everything is the same except the menu no longer catches keypresses in Update() for when you're actually binding the key - and it's no longer in an unnecessary class.

Are you sure you didn't just have noclip toggled off? lol

**Comment by M-Gardevoir** [comment]
> I can't replicate and don't see why the old system would work and the new one wouldn't. Everything is the same except the menu no longer catches keypresses in Update() for when you're actually binding the key - and it's no longer in an unnecessary class.
> 
> Are you sure you didn't just have noclip toggled off? lol

Yea it was toggled off god dammit lol. 
10mn searching why it didn't works for me on the code to find out i'm retarded. 

Thanks anyways.
