### ISSUE TITLE
Night Vision makes the map darker than brighter

### ISSUE THREAD

**Issue by xAstroBoy** [KaylinOwO/Project-Apparatus#55]
Title, maybe a better way to have a full working night vision?

**Comment by KaylinOwO** [comment]
There's a slider that controls how bright you want it - definitely never gets darker than the default

**Comment by xAstroBoy** [comment]
> There's a slider that controls how bright you want it - definitely never gets darker than the default

Where? i cannot find it anywhere in the menu.

**Comment by KaylinOwO** [comment]
> > There's a slider that controls how bright you want it - definitely never gets darker than the default
> 
> Where? i cannot find it anywhere in the menu.

it's directly below the night vision checkbox - make sure you have the latest version of the cheat.
