### ISSUE TITLE
Tons of errors when trying to compile from the sln

### ISSUE THREAD

**Issue by RapidOnGfuel** [KaylinOwO/Project-Apparatus#60]
![image](https://github.com/KaylinOwO/Project-Apparatus/assets/73676960/02745f79-c3ab-4b34-876b-a5b7345801c8)

![image](https://github.com/KaylinOwO/Project-Apparatus/assets/73676960/95231135-92fb-4a50-963f-36aba3cc94b1)

this is what the missing using is and i get a ton of errors when i try to compile how do i fix?

**Comment by vOuii** [comment]
Add references to the project from game files. If you're asking this why are you on github. YouTube plz. It tells you exactly what you need to know in the error code you provided

**Comment by vOuii** [comment]
https://youtu.be/LuDCJ90igrg?si=ieracj5gW1bqq1Ri

Project>add reference>lethal company folder>Lethal Company_data>Managed
Every .dll in there... add it.. use common sense and google the error next time? I'm sure these guys are getting slammed with silly things like this all time time ☹️

**Comment by Toaaa** [comment]
layer 8
