### ISSUE TITLE
Cheat hat keine Malware

### ISSUE THREAD

**Issue by Slaulie** [KaylinOwO/Project-Apparatus#62]
Huhu! 👋

Ich frage mich, da der Cheat ja von Toaaa mitgeschrieben wurde, wo denn die Malware im Cheat verbaut ist, denn ich kann sie nämlich nicht finden.
Bitte teilen Sie mit, wenn Sie mehr Informationen haben, oder Sie werden in Lasagne verwandelt.

MfG.
Bennedikt

**Comment by Anonymous691-source** [comment]
Hallo 👋

Der Cheat enthält keinen Virus oder Malware. Dieser Cheat wird von vielen Menschen sicher verwendet

**Comment by KaylinOwO** [comment]
I don't speak German

I'm unsure if you're a friend of Toaaa and you're just joking or not but Toaaa's pull requests were analyzed, all is safe.

**Comment by Slaulie** [comment]
I am releaved to hear this last time I downloaded Toaaaaaaaa's software he selled my wife
