### ISSUE TITLE
Needs a revert settings button.

### ISSUE THREAD

**Issue by IMODTOOMUCH** [KaylinOwO/Project-Apparatus#64]
Cant open up the "self" tab without the menu closing. prety sure i activated a setting in there that possibly causes it to crash

**Comment by daxelvbbz** [comment]
Happends me same

**Comment by daxelvbbz** [comment]
> Cant open up the "self" tab without the menu closing. prety sure i activated a setting in there that possibly causes it to crash
Happend me same

**Comment by benalopey** [comment]
I have the same problem too, it crashes the menu or something, and I can't interact with it. I only did the key bind for the third person, and it triggered the bug.

**Comment by daxelvbbz** [comment]
> I have the same problem too, it crashes the menu or something, and I can't interact with it. I only did the key bind for the third person, and it triggered the bug.

I just binded noclip and than the self button wont work again

**Comment by benalopey** [comment]
> > I have the same problem too, it crashes the menu or something, and I can't interact with it. I only did the key bind for the third person, and it triggered the bug.
> 
> when i binded noclip in self appartment it bugs like shi and the self appartment wont work again

I hope the Dev or Mod fixes this early, Ngl out of all of the Mod menus I downloaded this is the best one so far.

**Comment by daxelvbbz** [comment]
> > > I have the same problem too, it crashes the menu or something, and I can't interact with it. I only did the key bind for the third person, and it triggered the bug.
> > 
> > 
> > when i binded noclip in self appartment it bugs like shi and the self appartment wont work again
> 
> I hope the Dev or Mod fixes this early, Ngl out of all of the Mod menus I downloaded this is the best one so far.

![image](https://github.com/KaylinOwO/Project-Apparatus/assets/155793916/89b2974d-9e9f-4576-addd-d0c8f4afb4f4)
Real

**Comment by daxelvbbz** [comment]
There its not a form to solve it like i proof uninstalling lethal company changing to alt account reinstalling the cheat but it wont work

**Comment by benalopey** [comment]
> There its not a form to solve it? like i proof uninstalling lethal company changing to alt account reinstalling the cheat but it wont work

They've talked about this like two days ago, here you can check it out. https://github.com/KaylinOwO/Project-Apparatus/issues/56

**Comment by daxelvbbz** [comment]
Yeah but the problem was on old version of the mod menu

**Comment by daxelvbbz** [comment]
> > There its not a form to solve it? like i proof uninstalling lethal company changing to alt account reinstalling the cheat but it wont work
> 
> They've talked about this like two days ago, here you can check it out. #56
I FOUDN A SOLUTION

**Comment by daxelvbbz** [comment]
:D

**Comment by daxelvbbz** [comment]
![image](https://github.com/KaylinOwO/Project-Apparatus/assets/155793916/c472c395-6c5e-409d-8572-e0c7fe63bbcd)

**Comment by RaymondYarb** [comment]
What is the solotion for said issue?

**Comment by benalopey** [comment]
> ![image](https://private-user-images.githubusercontent.com/155793916/294653231-c472c395-6c5e-409d-8572-e0c7fe63bbcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjMxNDgsIm5iZiI6MTcwNDUyMjg0OCwicGF0aCI6Ii8xNTU3OTM5MTYvMjk0NjUzMjMxLWM0NzJjMzk1LTZjNWUtNDA5ZC04NTcyLWUwYzdmZTYzYmJjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwNjM0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWFhMTk3NTA4MjQzZTc5ZjNlZGFjNjU2MTQ0N2E2ZWJiYjQ4ZmE0YmY0ZDAyMzQ0NWM5NmIwOTQ4MTI1YmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iw4UrA-HVFC39LjEf-4Q4OlI6DODrUZgXptT5Rojww4)

Did you delete something? for it to work again? I'd like to know.

**Comment by KaylinOwO** [comment]
delete PASettings.json in C:\Users\%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company

sorry for the delay on a real fix - i'll prioritize it once im back to working on the cheat.

**Comment by benalopey** [comment]
> delete PASettings.json in C:\Users%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company
> 
> sorry for the delay on a real fix - i'll prioritize it once im back to working on the cheat.

WORKED ✅

Thank you so much for this. 

Also, I appreciate your teams work on this mod.

**Comment by daxelvbbz** [comment]
> delete PASettings.json in C:\Users%username%\AppData\LocalLow\ZeekerssRBLX\Lethal Company
> 
> sorry for the delay on a real fix - i'll prioritize it once im back to working on the cheat.

thats what i did sorry for the late
