### ISSUE TITLE
Suggestion: Language Menu

### ISSUE THREAD

**Issue by Slaulie** [KaylinOwO/Project-Apparatus#66]
Hello! 👋

I'd like to propose a new feature for the cheat: a Language Menu/Tab.

As you may have already guessed, this menu allows users to select and change the language of the cheat. This would be a valuable addition as there are many users worldwide who would appreciate gaining an unfair advantage over others but may not be fluent in English. Alternatively, you could implement a feature that automatically sets the cheat language to match the language the user is using in their game. Users from different countries could even contribute to their own language support by submitting an issue ticket on Github.

This would be an awesome feature for every user, enabling players from around the world to use the cheat in their preferred language.

Best regards,
Benedikt

**Comment by Toaaa** [comment]
This has already been implemented in pull request #61. We are currently checking whether the implementation makes sense and fits into the project and will implement it if that's the case.

**Comment by Slaulie** [comment]
> This has already been implemented in pull request #61. We are currently checking whether the implementation makes sense and fits into the project and will implement it if that's the case.

where my wife?

**Comment by Anonymous691-source** [comment]
> > This has already been implemented in pull request #61. We are currently checking whether the implementation makes sense and fits into the project and will implement it if that's the case.
> 
> where my wife? 192.168.10.1 dis u?

whats so offensive about this, i mean you are tryna find ops ☠️

**Comment by Toaaa** [comment]
Was implemented in 57abb379855c422460589ce379db8b2726ac9f9a
