### ISSUE TITLE
Suggestion: Anti Kick

### ISSUE THREAD

**Issue by Beerian** [KaylinOwO/Project-Apparatus#67]
Hi can you add an Anti Kick feature like https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/AntiKickPatch.cs

**Comment by vOuii** [comment]
I vouch this. Looks like a good paste to commit ☺️

**Comment by vOuii** [comment]
Trying my hardest to add this but I'm quite new to C#. Hopefully someone can add this before I do, otherwise it'll just be a lengthy wait :(

**Comment by vOuii** [comment]
I have added this feature just now, although I'm new to C# :D I have ran into an issue though, in where it for some reason is breaking player ESP. In the meantime, antikick definitely works with apparatus but I just need to fix this bug

**Comment by vOuii** [comment]
[Project-Apparatus-main.zip](https://github.com/KaylinOwO/Project-Apparatus/files/13854194/Project-Apparatus-main.zip)

Like this?

**Comment by vOuii** [comment]
I added a pull request. Hopefully it gets approved :D

**Comment by vOuii** [comment]
https://github.com/vOuii/Project-Apparatus - Source (if you wanna compile yourself)
https://github.com/vOuii/Project-Apparatus/releases/tag/release - Release
This is a fork if you wanna use it early before approved :)
![image](https://github.com/KaylinOwO/Project-Apparatus/assets/38688744/355a58d3-3a2e-47d9-b069-d743676b41ce)

**Comment by Stepd3D** [comment]
Apparently people can still kick

**Comment by vOuii** [comment]
Done, waiting for merge

**Comment by vOuii** [comment]
> Hi can you add an Anti Kick feature like https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/AntiKickPatch.cs

Done, Waiting for merge.

**Comment by Beerian** [comment]
Thank you sir 😇
