### ISSUE TITLE
INJECTOR IS CRASHING

### ISSUE THREAD

**Issue by endervale** [KaylinOwO/Project-Apparatus#77]
idk why but first my pc detected the injector as a threat then blocked it, then i disabled my anitvirus but the injector keeps crashing after i click to "refresh"

**Comment by kokoroko23** [comment]
how do u even get the injector

**Comment by realbillie** [comment]
[](https://github.com/warbler/SharpMonoInjector)

**Comment by realbillie** [comment]
> how do u even get the injector
> 
> 

https://github.com/warbler/SharpMonoInjector

**Comment by endervale** [comment]
> how do u even get the injector

i used the sharp mono injector from the tutorial video
btw whats the tutorial video link aggain ?

**Comment by realbillie** [comment]
> idk why but first my pc detected the injector as a threat then blocked it, then i disabled my anitvirus but the injector keeps crashing after i click to "refresh"

Make sure to have sharpmono .dll file in the same folder as the injector otherwise the refresh will just end the process.

Does not matter which video btw. There is heaps that explain the same thing!
