### ISSUE TITLE
Anti Kick Removed?

### ISSUE THREAD

**Issue by Stepd3D** [KaylinOwO/Project-Apparatus#79]
Anti kick is gone in new version?

**Comment by realbillie** [comment]
Yes but it can be re-added. I’m just implementing commands and new patches first. Then will release a big pull request :D with antikick too

On 10 Jan 2024, at 12:54, Steps3D ***@***.***> wrote:

﻿

Anti kick is gone in new version?

**Comment by realbillie** [comment]
> Anti kick is gone in new version?

Yes but it can be re-added. I’m just implementing commands and new patches first. Then will release a big pull request :D with antikick too

**Comment by Stepd3D** [comment]
Lets go! Hype

**Comment by realbillie** [comment]
> Lets go! Hype

All is working, just need to adjust things and add the antikick back in. Will be back home in about 3 and a half hrs. I have a friend who has been testing and fixing a few bugs up for me. The biggest one is the antikick breaking playerESP. This was a huge deal so credits will go to him when the commit is added! Honestly loving how it's coming along!

Also credit will go to winstxnhdw from ls-hax. Although I had to rewrite the entire scripts to support C# 4.8. The base of it helped a lot to implement such idea!

**Comment by HopeLight** [comment]
> > Lets go! Hype
> 
> All is working, just need to adjust things and add the antikick back in. Will be back home in about 3 and a half hrs. I have a friend who has been testing and fixing a few bugs up for me. The biggest one is the antikick breaking playerESP. This was a huge deal so credits will go to him when the commit is added! Honestly loving how it's coming along!
> 
> Also credit will go to winstxnhdw from ls-hax. Although I had to rewrite the entire scripts to support C# 4.8. The base of it helped a lot to implement such idea!

**Thank you so much,you try hard to solve about these probleam.**

**Comment by HopeLight** [comment]
In recent time,I'm interested in studying about auditing of code of lethal company also.

**Comment by realbillie** [comment]
Update, I'm just in the process of adding the /block radar command implemented into a checkbox in the self tab. This skips the radar when someone tries to "spectate" you when in the ship. But this does not stop dead players from spectating you if you are alive :)

**Comment by realbillie** [comment]
GET READY FOR UPDATE LADS! Just about to post up!

**Comment by Stepd3D** [comment]
Missing files on V 1.2.1 when generate solution?



Missing Scripts



-Clear commands.cs
-LevelsCommands.cs
-ScrapsCommand.cs
-Debugs.cs
-TimescaleCommand.cs
-UnlockablesCommand.cs
-DropCommand.cs
-FixCameraCommand.ca




Le jeu. 11 janv. 2024, à 04 h 17, Billie ***@***.***> a
écrit :
