### ISSUE TITLE
Issue when building project on Microsoft Visual Studio 2022

### ISSUE THREAD

**Issue by NebulaShinx** [KaylinOwO/Project-Apparatus#8]
When I follow the instructions on the video and set the drop down to release, click build, then click build solution, I get these errors:

![Screenshot 2023-12-29 205940](https://github.com/KaylinOwO/Project-Apparatus/assets/119905704/71f86846-63e3-464d-a3bd-e25bc9173e3f)

I also noticed that when the person in the video was done building the project, and opened the injector and lethal company, for the "assembly to inject" tab, they injected the DLL called "ProjectApparatus.dll", and I looked for it but couldn't find it in my Release folder like the person on the video did. So I was thinking maybe because the project didn't build correctly is why I can't find it?

I hope I am explaining everything correctly, and hope you can help me. 

Thank you!
@KaylinOwO @Toaaa @AnonGajo

**Comment by KaylinOwO** [comment]
Please follow the new guide - remember to download the latest version of the source as well 
https://www.youtube.com/watch?v=6AhJQLgt8Jc&feature=youtu.be
