### ISSUE TITLE
need help installing

### ISSUE THREAD

**Issue by detectiveclea** [KaylinOwO/Project-Apparatus#81]
can someone give me a step by step  explanation oon how to install this?

**Comment by tedzify** [comment]
- [**Step by step video guide**](https://www.youtube.com/watch?v=6AhJQLgt8Jc): How to build Project Pparatus
- [**UnknownCheats forum post**](https://www.unknowncheats.me/forum/lethal-company/616587-project-apparatus-lethal-company-cheat.html): For additional resources, go to the bottom part of the main post, find: "Guide (for people building from source)".
