### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Stepd3D** [KaylinOwO/Project-Apparatus#86]
Missing files on V 1.2.1 when generate solution?

**Comment by Stepd3D** [comment]
Missing Scripts (Clear commands.cs
-LevelsCommands.cs
-ScrapsCommand.cs
-Debugs.cs
-TimescaleCommand.cs
-UnlockablesCommand.cs
-DropCommand.cs
-FixCameraCommand.ca

**Comment by realbillie** [comment]
Thanks for this! I'll have a look and patch it up when I get home after I finish work 😊

**Comment by Stepd3D** [comment]
No problems!

**Comment by realbillie** [comment]
> Missing Scripts (Clear commands.cs
> 
> -LevelsCommands.cs
> 
> -ScrapsCommand.cs
> 
> -Debugs.cs
> 
> -TimescaleCommand.cs
> 
> -UnlockablesCommand.cs
> 
> -DropCommand.cs
> 
> -FixCameraCommand.cs

I have now just deleted these as they were just debugging commands with no real purpose
