### ISSUE TITLE
Nightvision Brightness needs to be toned down a bit

### ISSUE THREAD

**Issue by LordIgnis** [KaylinOwO/Project-Apparatus#9]
While everything else is fantastically designed so far as I've tested, my biggest gripe next to the lack of keybinds and the "Hear Everyone" seemingly doesn't work, the brightness if the nightvision is insanely bright compared to every other cheat available that offers nightvision. Whatever parameters this cheats nightvision is set to should be changed to what UrbanJoker's Infinite Company's settings are because those are perfect (and that's what I used before this one) Im having to regularly turn the cheat on and off because of how obnoxious it gets and even changing the games built in brightness setting doesnt help much of anything, it seems like it doesnt effect the brightness so much as cranks up the contrast which also effects how the game looks quality wise while exploring.

**Comment by KaylinOwO** [comment]
I changed the night vision intensity back to the original value Infinite Company used 
May make this optional in the future
