### ISSUE TITLE
Suggestion: Purple Suit

### ISSUE THREAD

**Issue by jaydenthedes** [KaylinOwO/Project-Apparatus#90]
Hello I have a suggestion of adding the Purple Suit to the "Upgrades" tab. Thank you.

**Comment by chuxiaaaa** [comment]
How do I get the purple suit? Can I buy it in the store? I haven't found it anywhere

**Comment by TheGreenBandit** [comment]
> How do I get the purple suit? Can I buy it in the store? I haven't found it anywhere

Its one of the upgrades, between 14 - 17 check in dnspy for the complete upgrade list as the one in here aint full

**Comment by chuxiaaaa** [comment]
> > How do I get the purple suit? Can I buy it in the store? I haven't found it anywhere
> 
> Its one of the upgrades, between 14 - 17 check in dnspy for the complete upgrade list as the one in here aint full

I will check, if I find any, I will update the upgrade list.

**Comment by chuxiaaaa** [comment]
I have refactored the entire ship upgrade code, and the issue has been resolved. In the future, new upgrades added in game version updates will also be automatically obtained.

Now just wait for the merge of #91 pull request or clone my repository directly to solve your problem

![FM(YV9C47L$}U}XHTZ4%))0](https://github.com/KaylinOwO/Project-Apparatus/assets/62934376/ace2593e-121e-451a-a32a-73c92f6d3895)

**Comment by jaydenthedes** [comment]
I added it myself but thanks now its in the source and better than I could have done it.
