### ISSUE TITLE
Where is the version with AntiKick now?

### ISSUE THREAD

**Issue by Stepd3D** [KaylinOwO/Project-Apparatus#92]
?

**Comment by realbillie** [comment]
Check my profile. I don't support anything other than ENG. sorry to everyone but I don't agree with the fact that it is in fact being sold.

**Comment by realbillie** [comment]
If you want source, you can contact me on discord lylyisbae

**Comment by Beerian** [comment]
> If you want source, you can contact me on discord lylyisbae

added you on discord - berxzz

**Comment by jaydenthedes** [comment]
> If you want source, you can contact me on discord lylyisbae

I just added you username - pv4t

**Comment by sword11247** [comment]
> If you want source, you can contact me on discord lylyisbae

i added too name is supernova
