### ISSUE TITLE
help I can't package it into a dll

### ISSUE THREAD

**Issue by a66a66a** [KaylinOwO/Project-Apparatus#94]
sir I don't understand what I did wrong. Can anyone tell me?
![1111111](https://github.com/KaylinOwO/Project-Apparatus/assets/156866148/16bcd1e8-4a41-4f2f-a547-227345045a96)

**Comment by a66a66a** [comment]
i have successfully repaired

**Comment by TheGreenBandit** [comment]
click close solution then if you have solved the issue

**Comment by a66a66a** [comment]
> click close solution then if you have solved the issue

okok thanks for reminding

**Comment by TheGreenBandit** [comment]
#L mom m in n Jo no

**Comment by ANCCC-hash** [comment]
I have met the same problem, please tell me how to solve the problem

**Comment by Toaaa** [comment]
> I have met the same problem, please tell me how to solve the problem

Please take a look at [this](https://github.com/Toaaa/PA-Updater).
