### ISSUE TITLE
Suggestion Ideas

### ISSUE THREAD

**Issue by Erzical** [KaylinOwO/Project-Apparatus#95]
I had a few ideas:

Troll menu
Give menu, so you can give yourself items. Or a chat menu so that you can /give command

**Comment by chuxiaaaa** [comment]
The client does not have permission to generate items, but you can obtain items through the store. For details, see the #91 pull request

**Comment by Erzical** [comment]
Makes sense, but what about a troll menu? He is still allowed to do that correct? Because I was thinking that it would be cool if you could spawn mines on people or something, etc.

**Comment by chuxiaaaa** [comment]
The client cannot generate items, enemies, turrets, and mines out of thin air. The information generated by the client is not recognized by the server. The functions that can be implemented are basically those that the player can do, such as generating a Masked, but this requires the consumption of a mask.
