### ISSUE TITLE
Possessing Enemies Feature ( Go to this Suggestion For More Like uhh Info )

### ISSUE THREAD

**Issue by TKarambit** [KaylinOwO/Project-Apparatus#96]
- Possessing Enemies Fix
Hello I Wanted To Ask Again..

Is It Possible To Use Entity's Special Ability, Like The Bracken Snap Ability
Since There's Already An Mod Where You Can Control The Enemy, With Its Ability.

So Please Add This Feature.

Here's The Link For The Mod To Take  A Closer look (  https://thunderstore.io/c/lethal-company/p/ControlCompany/ControlCompany/ )

**Comment by chuxiaaaa** [comment]
These are host-only features, and we recommend that you use this mod directly

**Comment by TKarambit** [comment]
Thank's For The Info
